### ISSUE TITLE
Not really an issue: LLVM

### ISSUE THREAD

**Issue by whitesec-au** [yhirose/pl0-jit-compiler#2]
@yhirose Not really an issue, but I would like to ask where did you learn how to create a JIT with LLVM, and has this API changed in subsequent LLVM versions?  I can't find any documentation that's clear enough to write a simple JIT like this.

Still, I'm installing LLVM 9.0 and having a go at the divide by zero issue.

Thanks, it's a really neat little JIT!

**Comment by yhirose** [comment]
@whitesec-au, sorry for the late reply... I just took a look at the official LLVM documentation and some blog articles on Internet. Mine is till using the old MCJIT. The current recommended API is ORCv2. When I have time, I'll try to change my code to use the latest API. https://llvm.org/docs/ORCv2.html

I have recently bought a book "[Learn LLVM 12](https://www.amazon.com/Learn-LLVM-12-beginners-libraries-ebook/dp/B08W8PJQW2/ref=sr_1_1?crid=2P3MHKH4TI9AJ&keywords=learn+llvm+12&qid=1654119003&sprefix=learn+llvm+12%2Caps%2C69&sr=8-1)". I recommend anyone who are seriously interested in implementing something with the latest LLVM API. I have just read the chapter regarding how to do 'exception handling', and I was able to support 'zero divide' problem properly in my pl0-jit-compiler. Hope it helps!
